workflows:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**/*"
db:
  - changed-files:
      - any-glob-to-any-file: "*.sqlite"
e2e:
  - changed-files:
      - any-glob-to-any-file: "e2e/**/*"
package:
  - changed-files:
      - any-glob-to-any-file: "package.json"
