import { DataTable } from "@/components/companies/data-table";

import { promises as fs } from "fs";
import path from "path";
import { Metadata } from "next";
import { z } from "zod";
import { taskSchema } from "@/components/companies/data/schema";
import { columns } from "@/components/companies/columns";

export const metadata: Metadata = {
  title: "StockSync : Companies",
  description: "Generated by create next app",
};

// Simulate a database read for tasks.
async function getTasks() {
  const data = await fs.readFile(
    path.join(process.cwd(), "src/components/companies/data/tasks.json")
  );

  const tasks = JSON.parse(data.toString());

  return z.array(taskSchema).parse(tasks);
}

export default async function Home() {
  const tasks = await getTasks();
  return (
    <section className="container grid items-center gap-6 pb-8 pt-6 md:py-10">
      <DataTable data={tasks} columns={columns} />
    </section>
  );
}
